-- MySQL Script generated by MySQL Workbench
<<<<<<< HEAD
-- 05/10/16 19:15:59
=======
-- 05/09/16 17:08:19
>>>>>>> 93280c724b4299bff21a295b8f8c09bf2467c4ea
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema canchaya
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema canchaya
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `canchaya` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `canchaya` ;

-- -----------------------------------------------------
-- Table `canchaya`.`provincia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `canchaya`.`provincia` ;

CREATE TABLE IF NOT EXISTS `canchaya`.`provincia` (
  `id` INT NOT NULL COMMENT '',
  `provincia_nombre` VARCHAR(50) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `canchaya`.`ciudad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `canchaya`.`ciudad` ;

CREATE TABLE IF NOT EXISTS `canchaya`.`ciudad` (
  `id` INT NOT NULL COMMENT '',
  `ciudad_nombre` VARCHAR(40) NOT NULL COMMENT '',
  `cp` SMALLINT NOT NULL COMMENT '',
  `id_provincia` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `cp` (`cp` ASC)  COMMENT '',
  INDEX `id_provincia` (`id_provincia` ASC)  COMMENT '',
  CONSTRAINT `fk_ciudad_provincia1`
    FOREIGN KEY (`id_provincia`)
    REFERENCES `canchaya`.`provincia` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `canchaya`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `canchaya`.`users` ;

CREATE TABLE IF NOT EXISTS `canchaya`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `admin` TINYINT(1) NOT NULL COMMENT '',
  `name` VARCHAR(40) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `email` VARCHAR(40) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `password` VARCHAR(40) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `updated_at` DATETIME NULL COMMENT '',
  `created_at` DATE NULL COMMENT '',
  `password_resets` VARCHAR(40) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL COMMENT '',
  `remember_token` INT NULL COMMENT '',
  UNIQUE INDEX `id` (`id` ASC)  COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `canchaya`.`establecimiento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `canchaya`.`establecimiento` ;

CREATE TABLE IF NOT EXISTS `canchaya`.`establecimiento` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(40) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `direccion` VARCHAR(80) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `tienevestuario` TINYINT(1) NOT NULL COMMENT '',
  `id_ciudad` INT NOT NULL COMMENT '',
  `id_usuario` INT UNSIGNED NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_establecimiento_ciudad1_idx` (`id_ciudad` ASC)  COMMENT '',
  INDEX `id_usuario` (`id_usuario` ASC)  COMMENT '',
  CONSTRAINT `fk_establecimiento_ciudad1`
    FOREIGN KEY (`id_ciudad`)
    REFERENCES `canchaya`.`ciudad` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_establecimiento_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `canchaya`.`users` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `canchaya`.`deporte`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `canchaya`.`deporte` ;

CREATE TABLE IF NOT EXISTS `canchaya`.`deporte` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `deporte` VARCHAR(40) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `canchaya`.`Superficie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `canchaya`.`Superficie` ;

CREATE TABLE IF NOT EXISTS `canchaya`.`Superficie` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `superficie` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `canchaya`.`cancha`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `canchaya`.`cancha` ;

CREATE TABLE IF NOT EXISTS `canchaya`.`cancha` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `id_establecimiento` INT NOT NULL COMMENT '',
  `nombre_cancha` VARCHAR(40) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `cant_jugadores` TINYINT NOT NULL COMMENT '',
  `tiene_luz` TINYINT(1) NOT NULL COMMENT '',
  `techada` TINYINT(1) NOT NULL COMMENT '',
  `id_deporte` INT NOT NULL COMMENT '',
  `id_superficie` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `id_establecimiento` (`id_establecimiento` ASC)  COMMENT '',
  INDEX `id_deporte` (`id_deporte` ASC)  COMMENT '',
  INDEX `id_superficie` (`id_superficie` ASC)  COMMENT '',
  CONSTRAINT `fk_cancha`
    FOREIGN KEY (`id_establecimiento`)
    REFERENCES `canchaya`.`establecimiento` (`id`),
  CONSTRAINT `fk_deporte`
    FOREIGN KEY (`id_deporte`)
    REFERENCES `canchaya`.`deporte` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_superficie`
    FOREIGN KEY (`id_superficie`)
    REFERENCES `canchaya`.`Superficie` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `canchaya`.`migrations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `canchaya`.`migrations` ;

CREATE TABLE IF NOT EXISTS `canchaya`.`migrations` (
  `migration` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `batch` INT(11) NOT NULL COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `canchaya`.`Dia`
-- -----------------------------------------------------
<<<<<<< HEAD
CREATE TABLE IF NOT EXISTS `canchaya`.`Dia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Dia` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `canchaya`.`turnoAdmin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `canchaya`.`turnoAdmin` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_dia` INT NOT NULL,
  `horaInicio` TIME(5) NOT NULL,
  `horaFin` TIME(6) NOT NULL,
  `id_usuario_admin` INT UNSIGNED NOT NULL,
  `id_cancha` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_usuario_admin` (`id_usuario_admin` ASC),
  INDEX `id_cancha` (`id_cancha` ASC),
  INDEX `id_dia` (`id_dia` ASC),
  CONSTRAINT `fk_cancha_turnoadmin`
    FOREIGN KEY (`id_cancha`)
    REFERENCES `canchaya`.`cancha` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_usuario_turnoadmin`
    FOREIGN KEY (`id_usuario_admin`)
    REFERENCES `canchaya`.`users` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_dia`
    FOREIGN KEY (`id_dia`)
    REFERENCES `canchaya`.`Dia` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `canchaya`.`turnoUsuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `canchaya`.`turnoUsuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_turnoAdmin` INT NOT NULL,
  `fecha_inicio` DATETIME NOT NULL,
  `fecha_fin` DATETIME NOT NULL,
  `precio_cancha` DOUBLE NOT NULL,
  `adic_luz` TINYINT(1) NOT NULL,
  `precio_adicional` DOUBLE NOT NULL,
  `confirmado` TINYINT(1) NOT NULL,
  `pagado` TINYINT(1) NULL,
  `id_usuario` INT UNSIGNED NOT NULL,
  `estado` TINYINT NOT NULL COMMENT 'estado para decir si un turno esta aprobado, rechazado,cancelado, finalizado',
  PRIMARY KEY (`id`, `id_usuario`),
  INDEX `fk_turno_usuario1_idx` (`id_usuario` ASC),
  INDEX `id_turnoAdmin` (`id_turnoAdmin` ASC),
=======
DROP TABLE IF EXISTS `canchaya`.`turno` ;

CREATE TABLE IF NOT EXISTS `canchaya`.`turno` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `id_cancha` INT NOT NULL COMMENT '',
  `fecha_inicio` DATETIME NOT NULL COMMENT '',
  `fecha_fin` DATETIME NOT NULL COMMENT '',
  `precio_cancha` DOUBLE NOT NULL COMMENT '',
  `adic_luz` TINYINT(1) NOT NULL COMMENT '',
  `precio_adicional` DOUBLE NOT NULL COMMENT '',
  `confirmado` TINYINT(1) NOT NULL COMMENT '',
  `pagado` TINYINT(1) NULL COMMENT '',
  `id_usuario` INT UNSIGNED NOT NULL COMMENT '',
  `estado` TINYINT NOT NULL COMMENT 'estado para decir si un turno esta aprobado, rechazado,cancelado, finalizado',
  PRIMARY KEY (`id`, `id_usuario`)  COMMENT '',
  INDEX `INDEX` (`id_cancha` ASC)  COMMENT '',
  INDEX `fk_turno_usuario1_idx` (`id_usuario` ASC)  COMMENT '',
  CONSTRAINT `fk_turno`
    FOREIGN KEY (`id_cancha`)
    REFERENCES `canchaya`.`cancha` (`id`),
>>>>>>> 93280c724b4299bff21a295b8f8c09bf2467c4ea
  CONSTRAINT `fk_turno_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `canchaya`.`users` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_turnoAdmin`
    FOREIGN KEY (`id_turnoAdmin`)
    REFERENCES `canchaya`.`turnoAdmin` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `canchaya`.`provincia`
-- -----------------------------------------------------
START TRANSACTION;
USE `canchaya`;
INSERT INTO `canchaya`.`provincia` (`id`, `provincia_nombre`) VALUES (1, 'Buenos Aires');
INSERT INTO `canchaya`.`provincia` (`id`, `provincia_nombre`) VALUES (2, 'Rio Negro');

COMMIT;


-- -----------------------------------------------------
-- Data for table `canchaya`.`ciudad`
-- -----------------------------------------------------
START TRANSACTION;
USE `canchaya`;
INSERT INTO `canchaya`.`ciudad` (`id`, `ciudad_nombre`, `cp`, `id_provincia`) VALUES (1, 'Bahia Blanca', 8000, 1);
INSERT INTO `canchaya`.`ciudad` (`id`, `ciudad_nombre`, `cp`, `id_provincia`) VALUES (2, 'Allen', 8328, 2);
INSERT INTO `canchaya`.`ciudad` (`id`, `ciudad_nombre`, `cp`, `id_provincia`) VALUES (3, 'San Antonio Oeste', 8269, 2);

COMMIT;


-- -----------------------------------------------------
-- Data for table `canchaya`.`deporte`
-- -----------------------------------------------------
START TRANSACTION;
USE `canchaya`;
INSERT INTO `canchaya`.`deporte` (`id`, `deporte`) VALUES (1, 'Futbol');
INSERT INTO `canchaya`.`deporte` (`id`, `deporte`) VALUES (2, 'Tennis');
INSERT INTO `canchaya`.`deporte` (`id`, `deporte`) VALUES (3, 'Basket');

COMMIT;


-- -----------------------------------------------------
-- Data for table `canchaya`.`Superficie`
-- -----------------------------------------------------
START TRANSACTION;
USE `canchaya`;
INSERT INTO `canchaya`.`Superficie` (`id`, `superficie`) VALUES (1, 'Sintético');
INSERT INTO `canchaya`.`Superficie` (`id`, `superficie`) VALUES (2, 'Tierra');
INSERT INTO `canchaya`.`Superficie` (`id`, `superficie`) VALUES (3, 'Piso Flotante');

COMMIT;


-- -----------------------------------------------------
-- Data for table `canchaya`.`Dia`
-- -----------------------------------------------------
START TRANSACTION;
USE `canchaya`;
INSERT INTO `canchaya`.`Dia` (`id`, `Dia`) VALUES (1, 'Lunes');
INSERT INTO `canchaya`.`Dia` (`id`, `Dia`) VALUES (2, 'Martes');
INSERT INTO `canchaya`.`Dia` (`id`, `Dia`) VALUES (3, 'Miércoles');
INSERT INTO `canchaya`.`Dia` (`id`, `Dia`) VALUES (4, 'Jueves');
INSERT INTO `canchaya`.`Dia` (`id`, `Dia`) VALUES (5, 'Viernes');
INSERT INTO `canchaya`.`Dia` (`id`, `Dia`) VALUES (6, 'Sábado');
INSERT INTO `canchaya`.`Dia` (`id`, `Dia`) VALUES (7, 'Domingo');

COMMIT;

